---
- name: Load variables
  include_vars: chroot.yml

- name: Run all tasks
  include_tasks:
    file: "chroot/{{ item }}"
  loop:
    - clock.yml
    - languages.yml
    - user.yml
    - pacman.yml
    - systemd.yml
    - swap.yml

- name: Extra task for vagrant install
  include_tasks:
    file: "chroot/vagrant.yml"
  when: sugar_vagrant|bool

- name: Unmount partitions
  mount:
    path: "{{ item }}"
    state: unmounted
  loop:
    - /mnt/boot
    - /mnt
  ignore_errors: true
  notify: restart message
