---
- name: Set hostname
  lineinfile:
    path: /etc/hostname
    create: true
    line: "{{ hostname }}"

# NetworkManager
- name: Copy config files to /etc/NetworkManager/conf.d/
  copy:
    src: "files/chroot/{{ item }}"
    dest: "/etc/NetworkManager/conf.d/{{ item }}"
  loop:
    - 10-dhclient.conf
    - 20-dns.conf
    - 30-mac-randomization.conf

- name: Enable/Disable NetworkManager related systemd services
  systemd:
    enabled: "{{ item.enabled | bool }}"
    name: "{{ item.name }}"
  loop:
    - { name: "NetworkManager", enabled: "true" }
    - { name: "systemd-resolved", enabled: "true" }
    - { name: "systemd-networkd", enabled: "false" }

# hibernate == suspend
- name: Make Hibernate same as Suspend
  replace:
    path: /etc/systemd/logind.conf
    regexp: "^#HandleHibernateKey.*$"
    replace: "HandleHibernateKey=suspend"
