---
- name: Set hostname
  lineinfile:
    path: /etc/hostname
    create: true
    line: "{{ hostname }}"

# NetworkManager
- name: Copy config files to /etc/NetworkManager/conf.d/
  copy:
    src: "files/chroot/{{ config }}"
    dest: "/etc/NetworkManager/conf.d/{{ config }}"
  loop:
    - 10-dhclient.conf
    - 20-dns.conf
    - 30-mac-randomization.conf
  loop_control:
    loop_var: config

- name: Enable/Disable NetworkManager related systemd services
  systemd:
    enabled: "{{ service.enabled | bool }}"
    name: "{{ service.name }}"
  loop:
    - { name: "NetworkManager", enabled: "true" }
    - { name: "systemd-resolved", enabled: "true" }
    - { name: "systemd-networkd", enabled: "false" }
  loop_control:
    loop_var: service

# hibernate == suspend
- name: Make Hibernate same as Suspend
  replace:
    path: /etc/systemd/logind.conf
    regexp: "^#HandleHibernateKey.*$"
    replace: "HandleHibernateKey=suspend"

# swap
- name: Create /swapfile
  block:
    # https://wiki.archlinux.org/index.php/Swap#Swap_file
    - name: Custom commands for btrfs filesystem
      command:
        cmd: "{{ command }}"
      loop:
        - truncate -s 0 /swapfile
        - chattr +C /swapfile
        - btrfs property set /swapfile compression none
      loop_control:
        loop_var: command

    - name: Create /swapfile with dd
      command:
        cmd: "dd if=/dev/zero of=/swapfile bs=1M count={{ chroot_swapsize }}"

    - name: Set permissions on /swapfile
      file:
        path: /swapfile
        mode: "0600"

    - name: Write swap header
      command:
        cmd: mkswap /swapfile
      changed_when: false

    - name: Add entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "/swapfile none swap sw 0 0"
