---
# password_hash('sha512') uses a different random salt each time
- name: Create new user
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
    password: "{{ user_passwd | password_hash('sha512') }}"
    groups: "{{ user_groups }}"

- name: Update root password
  user:
    name: root
    password: "{{ root_passwd | password_hash('sha512') }}"

- name: Copy sudo template
  template:
    src: "templates/chroot/sudo_user.j2"
    dest: "/etc/sudoers.d/{{ user }}"
    mode: "0440"
    validate: "visudo -c %s"
