---
# password_hash('sha512') uses a different random salt each time
- name: Create new user
  user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
    password: "{{ chroot_user_passwd | password_hash('sha512') }}"
    groups: "{{ user_groups }}"

- name: Setup vagrant ssh for user - copy the already existing vagrant ssh key
  copy:
    src: /home/vagrant/.ssh
    dest: "{{ user_home }}/.ssh"
    remote_src: true
  when: sugar_vagrant|bool

- name: Update root password
  user:
    name: root
    password: "{{ chroot_root_passwd | password_hash('sha512') }}"

- name: Copy sudo template
  template:
    src: "templates/chroot/sudo_user.j2"
    dest: "/etc/sudoers.d/{{ user }}"
    mode: "0440"
    validate: "visudo -c %s"
