---
chroot_swapsize_mb: "16384"

# required by templates/chroot/mirrorupgrade.hook.j2
chroot_reflector_cmd: "reflector -c 'United States' -l 50 -a 24 --sort rate \
  -p http -p https --save /etc/pacman.d/mirrorlist"
