# Configure python
---
- include_vars: master/python.yml

- include_role:
    name: scenario
  vars:
    pacman_pkgs: "{{ python_pacman_pkgs }}"
    files_to_remove: "{{ python_files_to_remove }}"

- name: User commands for python
  block:
    - name: Ensure pip3, runs everytime because if python upgrades, need to upgrade pip as well
      command:
        cmd: python -m ensurepip -U --user

    - name: Install or Update favorite pkgs
      pip:
        name: "{{ python_pkgs }}"
        extra_args: --user --upgrade
        chdir: "{{ user_home }}"
        executable: "{{ user_home }}/.local/bin/pip"

  become: true
  become_user: "{{ user }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ user_home }}/.local/bin"
