# Configure zsh and oh-my-zsh /w autosuggestions and custom theme
---
- include_vars: master/zsh.yml

- include_role:
    name: scenario
  vars:
    pacman_pkgs: "{{ zsh_pacman_pkgs }}"
    dirs_user: "{{ zsh_dirs_user }}"
    dotfiles_user: "{{ zsh_dotfiles_user }}"
    git_repos: "{{ zsh_git_repos }}"

- name: "Make zsh default shell for {{ user }} in /etc/passwd"
  lineinfile:
    path: /etc/passwd
    regex: "^sugar.*$"
    line: "{{ user }}:x:1000:1000::{{ user_home }}:/usr/bin/zsh"

- name: Setup zsh autocompletion for binaries
  shell:
    cmd: "{{ item.cmd }} > {{ item.dest }}"
    warn: false
  loop: "{{ zsh_completion_commands }}"

- name: User commands for zsh
  block:
    # 'item' is absolute path to symlink source file
    - name: Symlink all zshrc.d/*
      file:
        src: "{{ item }}"
        dest: "{{ user_home }}/.zshrc.d/{{ item | basename }}"
        state: link
        force: true
      loop: "{{ lookup('fileglob', sugar_dotfiles + '/zsh/zshrc.d/*', wantlist=True) }}"

  become: true
  become_user: "{{ user }}"
