---
- name: Install required package
  community.general.pacman:
    name: "{{ pacman_pkgs }}"

- name: Create directories
  import_tasks: create_dirs.yml

- name: Symlink dotfiles
  import_tasks: symlink_dotfiles.yml

- name: Remove files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_remove }}"

- name: Download, extract and install remote binaries
  import_tasks: remote_binaries.yml

- name: Clone git repos
  import_tasks: clone_git_repos.yml

- name: Refresh zsh completions
  import_tasks: completions.yml
