---
- name: Download, extract and install binaries from archive
  unarchive:
    src: "{{ item.urlfmt | regex_replace('%%', item.version) }}"
    dest: "{{ user_home }}/.local/bin/"
    exclude:
      - "*README.md"
      - "*LICENSE"
      - "*arm*"
      - "*darwin*"
      - "*windows*"
    extra_opts:
      - --transform
      - "s/^.*/{{ item.name }}/"
    mode: "0755"
    remote_src: true
  loop: "{{ remote_bin_archives }}"

- name: Download remote binaries
  get_url:
    url: "{{ item.urlfmt | regex_replace('%%', item.version) }}"
    dest: "{{ user_home }}/.local/bin/{{ item.name }}"
    mode: "0755"
  loop: "{{ remote_bin }}"
