---
- name: Symlink dotfiles (root)
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop: "{{ dotfiles_root }}"

- name: User commands
  block:
    - name: Symlink dotfiles (user)
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: true
      loop: "{{ dotfiles_user }}"

  become: true
  become_user: "{{ user }}"
