---
- name: Fail if internet is unavailable
  shell:
    cmd: "curl -Lk {{ google }} --retry 5 --silent > /dev/null"
    warn: false

- name: Check sugar_stage variable
  fail:
    msg: "Invalid value for sugar_stage: {{ sugar_stage }}"
  when: sugar_stage not in ['bootstrap', 'chroot', 'master']

- name: Run bootstrap stage
  include_tasks:
    file: bootstrap/main.yml
  when: sugar_stage == 'bootstrap'

- name: Run chroot stage
  include_tasks:
    file: chroot/main.yml
  when: sugar_stage == 'chroot'

- name: Run master stage
  include_tasks:
    file: master/main.yml
  when: sugar_stage == 'master'
