---
docker_pacman_pkgs:
  - docker # Pack, ship and run any application as a lightweight container
  - docker-compose # Fast, isolated development environments using Docker
  - docker-machine # Machine management for a container-centric world

docker_remote_bin:
  - {
      name: "hadolint",
      version: "1.21.0",
      urlfmt: "https://github.com/hadolint/hadolint/releases/download/v%%/hadolint-Linux-x86_64",
    }
