---
go_path: "{{ user_home }}/.go"
go_bin: "{{ go_path }}/bin"

go_pacman_pkgs:
  - gopls # Language server for Go programming language
  - go # Core compiler tools for the Go programming language
  - go-tools # Developer tools for the Go programming language
  - protobuf # Protocol Buffers - Google's data interchange format

go_dirs_user:
  - "{{ go_path }}"
  - "{{ go_bin }}"

go_remote_bin_archives:
  - {
      name: "golangci-lint",
      version: "1.36.0",
      urlfmt: "https://github.com/golangci/golangci-lint/releases/download/v%%/golangci-lint-%%-linux-amd64.tar.gz",
    }
  - {
      name: "grpcurl",
      version: "1.8.0",
      urlfmt: "https://github.com/fullstorydev/grpcurl/releases/download/v%%/grpcurl_%%_linux_x86_64.tar.gz",
    }
  - {
      name: "goreleaser",
      version: "0.155.1",
      urlfmt: "https://github.com/goreleaser/goreleaser/releases/download/v%%/goreleaser_Linux_x86_64.tar.gz",
    }

go_pkgs:
  - github.com/spf13/cobra/cobra # CLI program generator
  - google.golang.org/protobuf/cmd/protoc-gen-go # protoc plugin
  - google.golang.org/grpc/cmd/protoc-gen-go-grpc # protoc grpc plugin
