---
i3_pacman_pkgs:
  - i3-wm # An improved dynamic tiling window manager
  - i3lock # Improved screenlocker based upon XCB and PAM
  - i3status # Generates status bar to use with i3bar, dzen2 or xmobar
  - dmenu # Generic menu for X (application launcher)
  - pango # A library for layout and rendering of text
  - flameshot # Powerful yet simple to use screenshot software
  - alacritty # A cross-platform, GPU-accelerated terminal emulator
  - ttf-hack # A hand groomed and optically balanced typeface based on Bitstream Vera Mono.
  - redshift # Adjusts the color temperature of your screen according to your surroundings.
  - pulseaudio # A featureful, general-purpose sound server
  - pavucontrol # PulseAudio Volume Control

i3_dirs_user:
  - "{{ user_home }}/.config/i3"
  - "{{ user_home }}/.config/alacritty"

i3_dotfiles_user:
  - {
      src: "{{ sugar_dotfiles }}/i3/config",
      dest: "{{ user_home }}/.config/i3/config",
    }
  - {
      src: "{{ sugar_dotfiles }}/i3/i3status.conf",
      dest: "{{ user_home }}/.i3status.conf",
    }
  - {
      src: "{{ sugar_dotfiles }}/i3/redshift.conf",
      dest: "{{ user_home }}/.config/redshift.conf",
    }
  - {
      src: "{{ sugar_dotfiles }}/i3/alacritty.yml",
      dest: "{{ user_home }}/.config/alacritty/alacritty.yml",
    }
