---
k8s_pacman_pkgs:
  - kubectl # Kubernetes.io client binary
  - k9s # TUI for managing Kubernetes clusters and pods\
  - helm # The Kubernetes Package Manager
  - eksctl # Command line tool for creating clusters on Amazon EKS

k8s_dirs_user:
  - "{{ user_home }}/.kube"

k8s_remote_bin:
  - {
      name: kind,
      version: "0.10.0",
      urlfmt: "https://github.com/kubernetes-sigs/kind/releases/download/v%%/kind-linux-amd64",
    }
  - {
      name: skaffold,
      version: "1.19.0",
      urlfmt: "https://storage.googleapis.com/skaffold/releases/v%%/skaffold-linux-amd64",
    }

k8s_remote_bin_archives:
  - {
      name: krew,
      version: "latest",
      urlfmt: "https://github.com/kubernetes-sigs/krew/releases/%%/download/krew.tar.gz",
    }

k8s_helm_repositories:
  - { name: stable, url: "https://charts.helm.sh/stable" }
  - { name: bitnami, url: "https://charts.bitnami.com/bitnami" }
  - { name: k8s-at-home, url: "https://k8s-at-home.com/charts/" }
