---
X_pacman_pkgs:
  - xorg-server # Xorg X server
  - xorg-xrandr # Primitive command line interface to RandR extension
  - xorg-xprop # Property displayer for X (used /w i3 to set default window for a program)
  - xorg-xinit # X.Org initialisation program
  - xorg-xauth # X.Org authorization settings program (manipulate ~/.Xauthority)
  - xorg-xset # User preference utility for X (used in .xinitrc for power saving options)
  - xorg-xbacklight # RandR-based backlight control application
  - xorg-xinput # Small commandline tool to configure devices

X_dirs_root:
  - /etc/X11/xorg.conf.d

X_dotfiles_root:
  - {
      src: "{{ sugar_dotfiles }}/X/00-custom.conf",
      dest: "/etc/X11/xorg.conf.d/00-custom.conf",
    }

X_dotfiles_user:
  - { src: "{{ sugar_dotfiles }}/X/xinitrc", dest: "{{ user_home }}/.xinitrc" }
  - {
      src: "{{ sugar_dotfiles }}/X/xserverrc",
      dest: "{{ user_home }}/.xserverrc",
    }
