---
name: ci

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, master]
  # nightly builds @3am, on latest commit to default branch == 'master'
  schedule:
    - cron: "0 3 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ansible-lint
        run: make anslint

      - name: packer-lint
        run: make paclint

  build:
    # Virtualbox and Vagrant only available on macos-10.15 (catalina) gh runner
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
    runs-on: macos-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2

      - name: packer-build
        run: make build
